language: android
before_install:
 - chmod +x gradlew
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tool
    # The BuildTools version used by your project
    - build-tools-25.1.0
    # The SDK version used to compile your project
    - android-25
	- extra-android-m2repository

jdk:
	-oraclejdk8